Add information about domains and CloudFlare.
roboticsoutreach/kb pull request #80
Opened 2024-05-23 23:40 UTC by inventor02

2024-05-23 23:53 UTC, tpoomlmly requested changes
`sourcebots.co.uk` is registered with Hover

Also, could you add info about `robohack.co.uk`?

2024-05-23 23:53 UTC, tpoomlmly commented on docs/society/domains.md
> +Currently we do not know who owns this domain or where it is registered. We think its Andy Barrett-Sprott.
```suggestion
Currently we do not know who owns this domain or where it is registered. We think it's Andy Barrett-Sprott.
```

2024-05-24 00:11 UTC, inventor02 commented on docs/society/domains.md
> +Currently we do not know who owns this domain or where it is registered. We think its Andy Barrett-Sprott.
all done :)

2024-05-24 00:28 UTC, tpoomlmly approved these changes

2024-05-24 00:28 UTC, merged